name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Application with Debug
        env:
          # Keep existing secrets
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          # Add debug flags
          NEXT_DEBUG: 'clerk*'
          CLERK_DEBUG: '1'
          NODE_OPTIONS: '--inspect'
        run: |
          npm run build
          # Preserve source maps
          cp -r .next/static/. .next/server/static/

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SWATTS_SSH_KEY }}

      - name: Copy Build Files to Server
        run: |
          rsync -avz --delete \
            --include='.next/**' \
            --include='node_modules/**' \
            --include='package*' \
            --include='next.config.js' \
            --exclude='*' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ swatts@209.38.77.21:/home/swatts/Invoicer

      - name: Restart Application with Debug
        run: |
          ssh -o StrictHostKeyChecking=no swatts@209.38.77.21 '
            cd /home/swatts/Invoicer
            pm2 delete Invoicer || true
            pm2 start npm --name "Invoicer" -- \
              --start -- \
              --inspect \
              -r source-map-support/register \
              -r ./utils/debug-get-auth.ts
            pm2 save'
